apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaserver
spec:
  selector:
    matchLabels:
      app: javaserver
  template:
    metadata:
      labels:
        app: javaserver
    spec:
      containers:
      - name: javaserver
        image: javaserver
        ports:
        - containerPort: 3000
