name: CD Gitops

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    environment: gitops
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Image to Dockerhub
      uses: docker/build-push-action@v1.1.0
      with: 
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ vars.REPOSITORY }}/gitopsfc
        tags: ${{ github.sha }},latest
      
    - name: Setup kustomize
      uses: imranismail/setup-kustomize@v1
      with:
        kustomize-version: "3.6.1"

    - name: Update Kubernetes resources
      env:
        REPOSITORY: ${{ vars.REPOSITORY }}
      run: |
        cd k8s
        kustomize edit set image javaserver=$REPOSITORY/gitopsfc:$GITHUB_SHA

    - name: Commit
      run: |
        git config --local user.mail "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -am "Bump docker version"

    - name: Push
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ vars.REPOSITORY }}/gitopsfc
